error_type: ValidationError
error_module: pydantic_core._pydantic_core
message: "2 validation errors for NodeManagerInputState\nversion\n  Field required\
  \ [type=missing, input_value={'validation_target': 'va...'field2': 'not_an_int'}},\
  \ input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing\n\
  input_field\n  Field required [type=missing, input_value={'validation_target': 'va...'field2':\
  \ 'not_an_int'}}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.11/v/missing"
validation_errors:
- type: missing
  loc:
  - version
  msg: Field required
  input:
    validation_target: valid_model
    data:
      field1: 123
      field2: not_an_int
  url: https://errors.pydantic.dev/2.11/v/missing
- type: missing
  loc:
  - input_field
  msg: Field required
  input:
    validation_target: valid_model
    data:
      field1: 123
      field2: not_an_int
  url: https://errors.pydantic.dev/2.11/v/missing
